### ISSUE TITLE
Change text of 'Karte' link on profile

### ISSUE THREAD

**Issue by lislis** [rubymonsters/slam-alphas#76]
to something like: 'Zurück zur Landesübersicht' or similar

**Comment by 1000miles** [comment]
Thanks for the suggestion, @lisis.

We tried to figure out how it would look like and think the best would be to keep

a) the wording as the linking path `/karte/de` 
b) one liner instead of two lines (looks better)

Screenshot 1: Two liner

<img width="1263" alt="00000284" src="https://cloud.githubusercontent.com/assets/4077916/24627283/8fd66330-18b4-11e7-8d25-68e0bb44ef5e.png">

Screenshot 2: One liner

<img width="1267" alt="00000286" src="https://cloud.githubusercontent.com/assets/4077916/24627299/a2f17356-18b4-11e7-8e1b-2d5b0ae2cc4c.png">

If that is okay for you, I am sending a PR now.

**Comment by 1000miles** [comment]
Otherwise we can change it later. :)

**Comment by lislis** [comment]
@1000miles Hey! I would suggest decoupling both links completely (and removing the `|`) and putting each one into a different block element. So it would not matter if only one or two are showing.
`Bearbeiten` will only be shown to admins or the logged in user herself. 
`Zurück zur Karte` will be visible to everyone. 
Wdyt?

**Comment by 1000miles** [comment]
@lislis Sounds good. Let's do it and see how it works. Thank you. :)
