### ISSUE TITLE
Add Profile Picture

### ISSUE THREAD

**Issue by sNeAkingEoN** [rubymonsters/slam-alphas#8]
Add a photo upload for the User's profile

**Comment by joecorcoran** [comment]
We might be lucky enough to get a short presentation on this topic from @lisbethmarianne...

**Comment by 1000miles** [comment]
Hi @joecorcoran Are we still waiting for @lisbethmarianne  or can I start to work on this ticket?  If yes, would you recommend to use the gem `papertrail` or `carrierwave` here? :)

**Comment by joecorcoran** [comment]
Ah we never got around to arranging a presentation and I don't want to put pressure on Katrin, so go ahead and start. I would personally pick Carrierwave, but you can decide. :)

**Comment by lisbethmarianne** [comment]
Wasn't carrierwave the thing I used and then we had to remove everything again because it doesn't work well with Heroku? Are you using Heroku? We followed these instructions: https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails

**Comment by joecorcoran** [comment]
Fair point! This seems to be the most recent advice I can find: 
http://stackoverflow.com/questions/37990519/carrierwave-heroku

--
Joe Corcoran
https://corcoran.io

**Comment by 1000miles** [comment]
Great, thank you very much for your inputs, @lisbethmarianne & @joecorcoran! :) Will investigate papertrail and carrierwave and decide for one. My first hunch is that carrierwave is a bit more complex but maybe a better gem to learn, if I am correct.

**Comment by 1000miles** [comment]
We need to specify the requirements for image uploads here, maybe @lislis and/or @joecorcoran can help? :) Thank you.

## Questions:

1. **General**
  1.1 How many images can a profile have at maximum? (Looking at the current front-end layout I assume there won't be a lot of space for more than 1 small image per profile, or?)
  1.2 Should the image(s) be clickable and lead to another page to see a bigger size of it?
2. **Validations:**
   2.1 What formats (png, jpg, etc.) should be acceptable? 
   2.2 What is the maximum size of an image that can be uploaded, e.g. 5MB? 
   2.3 What is the image size width & height limit to be uploaded ?
3. **Image Resizing:**
   3.1 What is the desirable resized image sizes, e.g. 100px x 100px (thumbnail), 150px x 150px (rectangle medium)?
   3.2 Where should we store the images, e.g. heroku, amazon web services s3, dropbox, etc.?
   3.3 Should we keep the original images after resizing or delete them? (I would go for deleting them to reduce cluttering images that finally block space)

---

@TODO

- [ ] Study `papertrail` and `carrierwave`
- [ ] Check and install dependencies, e.g. ImageMagick
- [ ] Install & configure `papertrail` or `carrierwave`
- [ ] Write tests for
   - image uploads
   - resizing
- [ ] Set up route & paths
   - directory for image uploads
   - directory for resized images
- [ ] Configure a `default_url` & placeholder when no image is uploaded
- [ ] Implement validations 
     - based on questions feedback
        - content-format, e.g. png, jpg, etc.
        - content-size (bytes, width & height)
     - required validations
        - content-type, e.g image
- [ ] Implement views
  - [ ] upload button
  - [ ] image gallery
- [ ] Provide error messages
     - i18n locale: text in english & german
- [ ] Document implementation 

---

@aydamacink @freddax @CarolinaGri @eine-sandra @sNeAkingEoN
Oops, this looks like a bigger task. I would love to do pairing with one of you. We then could do a walk-through with the rest of the group after each implementation? Any takers? What do you think?

**Comment by lislis** [comment]
Hey!
1. There will be one image per user-profile. These images are not clickable and don't do anything besides being there
2.1 png, jpg/jpeg, gif
2.2 A lot of slammers are also into photography but not so much into photo editing. So I assume that they would try uploading very large file sizes directly off their cameras. But instead of throwing an error I would prefer taking any file size and scale it down to something like 5MB or so (whatever zou see fit). Maybe even display a message saying 'Dein Bild war sehr groß, deswegen haben wir es etwas verkleinert'.
2.3 I don't think such a limit makes sense here. But a message that a square image is more useful because we'll use that size
3.1 We need the sizes 125x125 pixels and 300x300 pixels
3.2 I assume S3? @joecorcoran knows more about that
3.3 I would keep it in case we need to generate more/ different images for some cases. I would worry about overall clutter just yet, only once there are more than 1000 slammers registered ;)

**Comment by 1000miles** [comment]
Thanks a lot for your quick response, @lislis ! :) Check, 3.3 is for aspiring slammers! 😂

**Comment by lislis** [comment]
I added the profile pic in the user#show in https://github.com/rubymonsters/slam-alphas/pull/203
Closing this for the current scope of pictures
